#!/bin/sh

npm run build-server && npm run build-static && echo "build-finished!"

rm -rf ./var/server

mkdir var/server

cp -r ./server/dist/ ./var/server

cp ./server/package.json ./var/server/package.json

cd ./var/server

cd ../../

cp -r ./static/dist/ ./var/server/html

cd ./var/server

npm i && echo "deploy finished!"


