#!/bin/sh

npm run build-server && npm run build-static && npm run build-static-admin && echo "build-finished!"

rm -rf ./var/server

mkdir var/server

cp -r ./server/dist/ ./var/server

cp ./server/package.json ./var/server/package.json

node ./upload.js  && echo "deploy finished!"


