#!/bin/sh

npm run build-server && npm run build-static && npm run build-static-admin && echo "build-finished!"

rm -rf ./var/server

mkdir var/server

cp -r ./server/dist/ ./var/server

cp ./server/package.json ./var/server/package.json

cp -r ./static/dist/ ./var/server/html

cp -r ./static-admin/dist/ ./var/server/html-admin

cd ./var/server

npm i && echo "deploy finished!"


